#!/bin/bash
export LC_ALL=C
set -e -o pipefail

./contrib/scripts/check --path

if [ ! $(./contrib/scripts/check --tools="pip") ]; then
    make deps
fi

python -m pip install --upgrade pip
python -m setup build
python -m pip install --upgrade -r requirements.txt --user
python -m pip install git+https://github.com/dogecoin/ltc-scrypt --user
python -m setup install --user
