#!/bin/bash
export LC_ALL=C
set -e -o pipefail

./contrib/scripts/check --path

python -m venv .venv
source .venv/bin/activate
python -m setup build
python -m pip install --upgrade \
git+https://github.com/dogecoin/ltc-scrypt \
-r requirements.txt
