#!/bin/bash
export LC_ALL=C
set -e -o pipefail

./contrib/scripts/check --path

SYSUSER=$(source .env; echo $USERNAME)
USER_ID="$(id -u ${SYSUSER})"
GROUP_ID="$(id -g ${SYSUSER})"
make user
echo "Building container for system user: $SYSUSER ($(echo uid=$(id -u $SYSUSER)):$(echo gid=$(id -g $SYSUSER)))"
if [ ! -d ./db ]; then
    mkdir -p ./db
    ulimit -n 1048576
    $(./contrib/scripts/sudo) chown -R ${USER_ID}:${GROUP_ID} ./db
fi
docker build -t xanimo/electrumx \
--build-arg REPO=local \
--build-arg USERNAME=$SYSUSER \
--build-arg USER_ID=$USER_ID \
--build-arg GROUP_ID=$GROUP_ID \
. --no-cache
