#!/bin/bash
export LC_ALL=C
set -e -o pipefail

$(./contrib/scripts/sudo) apt-get update
# base dependencies
DEBIAN_FRONTEND=noninteractive \
$(./contrib/scripts/sudo) apt-get install -y --no-install-recommends \
automake \
gettext \
gosu \
python-is-python3 \
python3-cryptography \
python3-dotenv-cli \
python3-pip \
python3-setuptools \
zlib1g-dev \
libsnappy-dev \
libbz2-dev \
libgflags-dev \
liblz4-dev \
librocksdb-dev \
libleveldb-dev \
libboost-all-dev \
libsodium-dev \
libsecp256k1-0
$(./contrib/scripts/sudo) apt-get -y autoremove

if [[ $(cat ./certs/cert.pem) == "dummycert" ]]; then
    openssl req -x509 -newkey rsa:4096 -nodes -x509 -days 365 -subj "/O=ElectrumX" -keyout ./certs/privkey.pem -out ./certs/cert.pem -sha256 -days 365;
fi
