#!/bin/bash
export LC_ALL=C
set -e -o pipefail

if [ "$container" ]; then
docker run -d --net=host -v ./db/:/home/electrumx/db --name electrumx xanimo/electrumx:latest
else
./contrib/scripts/check --path
dotenv python electrumx_server
fi
