#!/bin/bash
export LC_ALL=C
set -e -o pipefail

USE_SUDO="sudo "
# get args
for i in "$@"
do
case $i in
    DOCKER=1)
        USE_SUDO=""
    ;;
    *)
        ERROR=1
    ;;
esac
done

if [ "$ERROR" ]; then
    echo "Unable to sense USE_SUDO. Please try again."
    exit $ERROR
fi

echo $USE_SUDO
