#!/bin/bash
export LC_ALL=C
set -e -o pipefail

INSIDE=$(./contrib/scripts/check --docker)
GROUPID=$(if [ "$INSIDE" ]; then echo "--gid $GROUP_ID"; else echo ""; fi)

# create system user to use inside docker container
SYSUSER=$(source .env; echo $USERNAME)
if [ ! $(getent group $SYSUSER) ]; then
    $SUDO addgroup --system $(source .env; echo $USERNAME) $GROUPID
fi
if [ ! $(getent passwd $SYSUSER) ]; then
    $SUDO adduser --system --no-create-home $SYSUSER --ingroup $SYSUSER
fi

SYSUSER=$(source .env; echo $USERNAME)
USER_ID=$(id -u $SYSUSER)
GROUP_ID=$(id -g $SYSUSER)
